export const LOGIN_REQUEST_SENDCODE = "LOGIN_REQUEST_SENDCODE"
export const LOGIN_REQUEST_SENDCODE_SUCCESS = "LOGIN_REQUEST_SENDCODE_SUCCESS"
export const LOGIN_REQUEST_SENDCODE_ERROR = "LOGIN_REQUEST_SENDCODE_ERROR"

export const LOGIN_REQUEST_TOKEN = "LOGIN_REQUEST_TOKEN"
export const LOGIN_REQUEST_TOKEN_SUCCESS = "LOGIN_REQUEST_TOKEN_SUCCESS"
export const LOGIN_REQUEST_TOKEN_ERROR = "LOGIN_REQUEST_TOKEN_ERROR"

export const LOGOUT = "LOGOUT"
