export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR"

export const LOGIN_TOKEN_RECEIVE = "LOGIN_TOKEN_RECEIVE"
export const LOGIN_TOKEN_SET = "LOGIN_TOKEN_SET"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_REQUEST_ERROR = "LOGOUT_REQUEST_ERROR"
