export const BOOKING_TABLES_REQUEST = "BOOKING_TABLES_REQUEST"
export const BOOKING_TABLES_REQUEST_SUCCESS = "BOOKING_TABLES_REQUEST_SUCCESS"
export const BOOKING_TABLES_REQUEST_ERROR = "BOOKING_TABLES_REQUEST_ERROR"

export const BOOKING_BOOK_REQUEST = "BOOKING_BOOK_REQUEST"
export const BOOKING_BOOK_REQUEST_SUCCESS = "BOOKING_BOOK_REQUEST_SUCCESS"
export const BOOKING_BOOK_REQUEST_ERROR = "BOOKING_BOOK_REQUEST_ERROR"
