export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_REQUEST_SUCCESS = "ORDER_LIST_REQUEST_SUCCESS"
export const ORDER_LIST_REQUEST_ERROR = "ORDER_LIST_REQUEST_ERROR"

export const ORDER_REQUEST = "ORDER_REQUEST"
export const ORDER_REQUEST_SUCCESS = "ORDER_REQUEST_SUCCESS"
export const ORDER_REQUEST_ERROR = "ORDER_REQUEST_ERROR"

export const ORDER_PAY_TINKOFFWEB_REQUEST = "ORDER_PAY_TINKOFFWEB_REQUEST"
export const ORDER_PAY_TINKOFFWEB_REQUEST_SUCCESS = "ORDER_PAY_TINKOFFWEB_REQUEST_SUCCESS"
export const ORDER_PAY_TINKOFFWEB_REQUEST_ERROR = "ORDER_PAY_TINKOFFWEB_REQUEST_ERROR"
