export const PROFILE_LOAD_REQUEST = "PROFILE_LOAD_REQUEST"
export const PROFILE_LOAD_REQUEST_SUCCESS = "PROFILE_LOAD_REQUEST_SUCCESS"
export const PROFILE_LOAD_REQUEST_ERROR = "PROFILE_LOAD_REQUEST_ERROR"

export const PROFILE_EDIT_REQUEST = "PROFILE_EDIT_REQUEST"
export const PROFILE_EDIT_REQUEST_SUCCESS = "PROFILE_EDIT_REQUEST_SUCCESS"
export const PROFILE_EDIT_REQUEST_ERROR = "PROFILE_EDIT_REQUEST_ERROR"
